os: linux
dist: bionic
language: node_js
node_js:
  - "14"
cache:
  - npm
  - yarn
install:
  - yarn global add gatsby-cli
  - yarn install
script:
  - yarn clean
  - yarn prod
before_deploy: yarn add-cname
deploy:
  provider: script
  script: yarn deploy
  skip_cleanup: true
  on:
    branch: master
