name: Notes Build and Deploy
on:
  push:
    branches: [ 'master' ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: mskelton/setup-yarn@v1
        with:
          node-version: '14.x'
      - name: Add Gatsby CLI to properly build the app
        run: yarn global add gatsby-cli
      - name: Install all dependencies
        run: yarn install
      - name: Perform a cleanup of existing artifacts
        run: yarn clean
      - name: Build app for production
        run: yarn prod
      - name: Add a CNAME for deployment
        run: yarn add-cname
      - name: Deploy to Github Pages
        run: yarn deploy
